### PR TITLE
added project icon

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Comment by gunjanmimo** [comment]
@ajay109458 sir, how to add the logo of this project in assets folder?

**Comment by ajay109458** [comment]
@gunjanmimo 

Instead of forking the repo..clone this repo itself and following the step in ReadMe.md

Refer task 1 of Link - https://github.com/CodingParkFunSeries/ResumeBuilder

**Comment by gunjanmimo** [comment]
@ajay109458 sir, i don't know why, when i am trying to push using https://github.com/CodingParkFunSeries/ResumeBuilder this link, I am getting an error, that's why i forked the repo

**Comment by ajay109458** [comment]
@gunjanmimo  I have given permissions. Please share screenshot with me on linkedin will try to solve the problem .

**Pull request closed without merging**
